from openact_core.tasks.templates import (
    PromptTemplate,
    get_template,
    get_templates,
    list_tasks,
    register_templates,
    register_lazy_loader,
    load_templates_from_dir,
    has_template,
    ANSWER_PREFIXES,
)
from openact_core.tasks.parsers import (
    AnswerParser,
    get_parser,
    list_parsers,
    NumericParser,
    MultipleChoiceParser,
    MCParser4,
    MCParser5,
    MathParser,
    TheoremQAParser,
    CodeParser,
    TruthfulQAParser,
    IFEvalParser,
    normalize_numeric,
    normalize_letter,
    normalize_text,
    normalize_math_expr,
    extract_boxed,
    find_last_number,
)
from openact_core.tasks.descriptor import (
    TaskDescriptor,
    get_descriptor,
    list_tasks_by_domain,
    list_tasks_by_type,
    register_task,
    TASK_DESCRIPTORS,
    EVAL_PARSER,
    EVAL_LLM_JUDGE,
    EVAL_SAFETY,
)

__all__ = [
    # templates
    "PromptTemplate",
    "get_template",
    "get_templates",
    "list_tasks",
    "register_templates",
    "register_lazy_loader",
    "load_templates_from_dir",
    "has_template",
    "ANSWER_PREFIXES",
    # parsers
    "AnswerParser",
    "get_parser",
    "list_parsers",
    "NumericParser",
    "MultipleChoiceParser",
    "MCParser4",
    "MCParser5",
    "MathParser",
    "TheoremQAParser",
    "CodeParser",
    "TruthfulQAParser",
    "IFEvalParser",
    "normalize_numeric",
    "normalize_letter",
    "normalize_text",
    "normalize_math_expr",
    "extract_boxed",
    "find_last_number",
    # descriptors
    "TaskDescriptor",
    "get_descriptor",
    "list_tasks_by_domain",
    "list_tasks_by_type",
    "register_task",
    "TASK_DESCRIPTORS",
    "EVAL_PARSER",
    "EVAL_LLM_JUDGE",
    "EVAL_SAFETY",
]