"""
Attack artifact loaders for safety data collection.

An *artifact* is a jailbreak prompt generated by an attack method (GCG, PAIR,
JBC, AutoDAN …) for a specific harmful behavior.  Artifacts are indexed by
``behavior_id`` and ``method``.

Supported sources
-----------------
- **Directory layout** — one JSON/JSONL per method under a root folder.
- **HuggingFace dataset** — ``JailbreakBench/JBB-Behaviors`` artifacts split.
- **Inline dict** — for testing.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


# -----------------------------------------------------------------------
# Data structure
# -----------------------------------------------------------------------

class Artifact:
    """A single attack prompt for a behavior."""

    __slots__ = ("behavior_id", "method", "prompt", "meta")

    def __init__(
        self,
        behavior_id: str,
        method: str,
        prompt: str,
        meta: Optional[Dict[str, Any]] = None,
    ):
        self.behavior_id = behavior_id
        self.method = method
        self.prompt = prompt
        self.meta = meta or {}

    def __repr__(self) -> str:
        return (
            f"Artifact(behavior={self.behavior_id!r}, "
            f"method={self.method!r}, len={len(self.prompt)})"
        )


# -----------------------------------------------------------------------
# Base loader
# -----------------------------------------------------------------------

class ArtifactLoader:
    """Abstract base for loading attack artifacts."""

    def get(self, behavior_id: str) -> List[Artifact]:
        raise NotImplementedError

    def list_methods(self) -> List[str]:
        raise NotImplementedError

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}()"


# -----------------------------------------------------------------------
# Directory-based loader
# -----------------------------------------------------------------------

class DirectoryArtifactLoader(ArtifactLoader):
    """Load artifacts from a directory of JSON / JSONL files.

    Expected layout::

        artifacts_dir/
            GCG.jsonl        # {"behavior_id": "...", "prompt": "..."}
            PAIR.jsonl
            ...

    or::

        artifacts_dir/
            GCG/
                behavior_001.json  # {"prompt": "..."}
                behavior_002.json
    """

    def __init__(
        self,
        artifacts_dir: str,
        methods: Optional[List[str]] = None,
    ):
        self.artifacts_dir = Path(artifacts_dir)
        self._filter_methods = set(m.upper() for m in methods) if methods else None
        self._index: Dict[str, List[Artifact]] = {}
        self._methods: List[str] = []
        self._loaded = False

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        if not self.artifacts_dir.exists():
            return

        # Pattern 1: JSONL files  method.jsonl
        for jsonl in self.artifacts_dir.glob("*.jsonl"):
            method = jsonl.stem.upper()
            if self._filter_methods and method not in self._filter_methods:
                continue
            self._methods.append(method)
            with open(jsonl, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    obj = json.loads(line)
                    bid = obj.get("behavior_id", obj.get("BehaviorID", ""))
                    prompt = obj.get("prompt", obj.get("jailbreak_prompt", ""))
                    if bid and prompt:
                        art = Artifact(behavior_id=bid, method=method, prompt=prompt)
                        self._index.setdefault(bid, []).append(art)

        # Pattern 2: JSON files  method.json  (list of items)
        for jf in self.artifacts_dir.glob("*.json"):
            method = jf.stem.upper()
            if self._filter_methods and method not in self._filter_methods:
                continue
            if method in self._methods:
                continue
            self._methods.append(method)
            with open(jf, "r", encoding="utf-8") as f:
                data = json.load(f)
            items = data if isinstance(data, list) else data.get("artifacts", [])
            for obj in items:
                bid = obj.get("behavior_id", obj.get("BehaviorID", ""))
                prompt = obj.get("prompt", obj.get("jailbreak_prompt", ""))
                if bid and prompt:
                    art = Artifact(behavior_id=bid, method=method, prompt=prompt)
                    self._index.setdefault(bid, []).append(art)

        # Pattern 3: sub-directories  method_dir/behavior_id.json
        for sub in self.artifacts_dir.iterdir():
            if not sub.is_dir():
                continue
            method = sub.name.upper()
            if self._filter_methods and method not in self._filter_methods:
                continue
            if method in self._methods:
                continue
            self._methods.append(method)
            for jf in sub.glob("*.json"):
                bid = jf.stem
                with open(jf, "r", encoding="utf-8") as f:
                    obj = json.load(f)
                prompt = obj.get("prompt", obj.get("jailbreak_prompt", ""))
                if prompt:
                    art = Artifact(behavior_id=bid, method=method, prompt=prompt)
                    self._index.setdefault(bid, []).append(art)

    def get(self, behavior_id: str) -> List[Artifact]:
        self._ensure_loaded()
        return self._index.get(behavior_id, [])

    def list_methods(self) -> List[str]:
        self._ensure_loaded()
        return list(self._methods)

    def __repr__(self) -> str:
        n = sum(len(v) for v in self._index.values()) if self._loaded else "?"
        return f"DirectoryArtifactLoader(dir={self.artifacts_dir}, n={n})"


# -----------------------------------------------------------------------
# HuggingFace JBB artifact loader
# -----------------------------------------------------------------------

class JBBArtifactLoader(ArtifactLoader):
    """Load artifacts from the JailbreakBench HuggingFace dataset.

    The ``JailbreakBench/JBB-Behaviors`` dataset has an ``artifacts``
    configuration with columns like ``GCG``, ``PAIR``, etc.
    """

    def __init__(
        self,
        methods: Optional[List[str]] = None,
        model_name: Optional[str] = None,
    ):
        self._filter_methods = methods
        self._model_name = model_name
        self._index: Dict[str, List[Artifact]] = {}
        self._methods: List[str] = []
        self._loaded = False

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        try:
            from datasets import load_dataset

            ds = load_dataset("JailbreakBench/JBB-Behaviors", "artifacts")
            # artifacts split is keyed by method columns
            for split_name in ds:
                for item in ds[split_name]:
                    bid = item.get("BehaviorID", item.get("behavior_id", ""))
                    # iterate over method columns
                    for key in item:
                        if key in ("BehaviorID", "behavior_id", "Goal", "Target"):
                            continue
                        method = key.upper()
                        if self._filter_methods and method not in [
                            m.upper() for m in self._filter_methods
                        ]:
                            continue
                        prompt = item[key]
                        if not prompt or not isinstance(prompt, str):
                            continue
                        if method not in self._methods:
                            self._methods.append(method)
                        art = Artifact(
                            behavior_id=bid, method=method, prompt=prompt
                        )
                        self._index.setdefault(bid, []).append(art)
        except Exception as e:
            import warnings
            warnings.warn(
                f"Failed to load JBB artifacts from HuggingFace: {e}. "
                "Continuing without artifacts.",
                UserWarning,
            )

    def get(self, behavior_id: str) -> List[Artifact]:
        self._ensure_loaded()
        return self._index.get(behavior_id, [])

    def list_methods(self) -> List[str]:
        self._ensure_loaded()
        return list(self._methods)


# -----------------------------------------------------------------------
# Dict-based loader (testing / scripting)
# -----------------------------------------------------------------------

class DictArtifactLoader(ArtifactLoader):
    """Simple in-memory artifact loader built from a dict.

    ``mapping``: ``{behavior_id: [(method, prompt), ...]}``
    """

    def __init__(self, mapping: Dict[str, List[tuple]]):
        self._index: Dict[str, List[Artifact]] = {}
        methods_set: set = set()
        for bid, entries in mapping.items():
            for method, prompt in entries:
                methods_set.add(method)
                self._index.setdefault(bid, []).append(
                    Artifact(behavior_id=bid, method=method, prompt=prompt)
                )
        self._methods = sorted(methods_set)

    def get(self, behavior_id: str) -> List[Artifact]:
        return self._index.get(behavior_id, [])

    def list_methods(self) -> List[str]:
        return list(self._methods)
